"""
RecruitSight — LinkedIn Report Compiler Agent
Aggregates all 4 LinkedIn agent outputs into a clean, standalone,
recruiter-friendly markdown report. This is a PURE LinkedIn report —
no GitHub comparison.
Uses gemini-2.5-pro for synthesis and report writing.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from agents.base import run_agent
from config import MODEL_PRO, REPORTS_DIR
from models.linkedin_schemas import (
    LinkedInReportOutput,
    LinkedInProfileOutput,
    LinkedInContentOutput,
    LinkedInInteractionOutput,
    LinkedInCredibilityOutput,
)

logger = logging.getLogger("recruitsight.linkedin_report_compiler")

SYSTEM_PROMPT = """You are the LinkedIn Report Compiler Agent for RecruitSight.

You receive the structured outputs from all 4 LinkedIn agents.
Your ONLY job is to compile them into a clean, professional markdown report.
You do NOT compare with GitHub. This report stands on LinkedIn evidence alone.

Your responsibilities:
1. Calculate a LINKEDIN COMPOSITE SCORE (weighted):
   - Profile Completeness Score:     15%
   - Content & Thought Leadership:   20%
   - Interaction & Engagement:       20%
   - Achievement & Credibility:      25%
   - Overall Professional Narrative: 20%
     (Does the full LinkedIn picture tell a coherent, credible career story?)

2. Assign a LINKEDIN PROFILE GRADE: A / B / C / D / F
   - A: 8.0-10.0 | B: 6.0-7.9 | C: 4.0-5.9 | D: 2.0-3.9 | F: 0.0-1.9

3. Write a 3-sentence EXECUTIVE SUMMARY a recruiter can read in 20 seconds.

4. Compile all agent sections into the report following this EXACT structure:

---
# 🔗 RecruitSight — LinkedIn Profile Report
**Profile:** <LinkedIn URL>
**Candidate Name:** <full_name>
**Current Role:** <current_role at company>
**Location:** <location>
**Analysis Date:** <today's date>
**LinkedIn Grade:** <A/B/C/D/F> (<composite score>/10)

---
## 🎯 Executive Summary
<3 sentences>

---
## 📊 Score Breakdown
| Dimension | Score | Weight |
|---|---|---|
| Profile Completeness | X/10 | 15% |
| Content & Thought Leadership | X/10 | 20% |
| Interaction & Engagement | X/10 | 20% |
| Achievement & Credibility | X/10 | 25% |
| Overall Professional Narrative | X/10 | 20% |
| **LINKEDIN COMPOSITE SCORE** | **X.X/10** | |

---
## 👤 Professional Profile
(Headline, experience, about section quality, employment timeline with gap/promotion flags, education, top skills)

---
## ✍️ Content & Thought Leadership
(Posting frequency, thought leadership level, expertise alignment, content breakdown, notable posts, red flags)

---
## 🤝 Interaction & Engagement
(Comment quality, professional tone, who they engage with, collaboration signals, personality insight, red flags)

---
## 🏆 Achievement & Credibility
(Certification pattern, skill endorsement credibility, certifications table, honors, notable absences, red flags, recruiter insight)

---
## ⚠️ Red Flags Summary
(Combined from ALL 4 agents)

---
## ✅ Strengths Summary
(Combined from ALL 4 agents)

---
## 👔 Recruiter Recommendation
**LinkedIn Verdict:** STRONG PROFILE | SOLID PROFILE | AVERAGE PROFILE | WEAK PROFILE | INCOMPLETE

<2-3 paragraph recommendation>

---
*Report generated by RecruitSight LinkedIn Analyzer*
---

RULES:
- Include ALL findings from ALL agents. If an agent failed, note it.
- Use exact scores from agent outputs for the weighted calculation.
- Write in professional, scannable language.
- The report_markdown field must contain the COMPLETE report."""


async def linkedin_report_compiler_agent(
    linkedin_url: str,
    profile_data: LinkedInProfileOutput | None,
    content_data: LinkedInContentOutput | None,
    interaction_data: LinkedInInteractionOutput | None,
    credibility_data: LinkedInCredibilityOutput | None,
) -> LinkedInReportOutput | None:
    """
    Compile all LinkedIn agent outputs into a final markdown report.
    """
    logger.info(f"📄 LinkedIn Report Compiler starting for: {linkedin_url}")

    # Build comprehensive input
    agent_outputs = {}
    agent_status = {}

    def _add(name, output):
        if output is not None:
            agent_outputs[name] = output.model_dump()
            agent_status[name] = "SUCCESS"
        else:
            agent_outputs[name] = None
            agent_status[name] = "FAILED"

    _add("linkedin_profile", profile_data)
    _add("linkedin_content", content_data)
    _add("linkedin_interaction", interaction_data)
    _add("linkedin_credibility", credibility_data)

    analysis_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    candidate_name = profile_data.full_name if profile_data else "Unknown"
    safe_name = candidate_name.replace(" ", "_")

    user_content = f"""Compile the final LinkedIn analysis report:

LINKEDIN URL: {linkedin_url}
CANDIDATE NAME: {candidate_name}
ANALYSIS DATE: {analysis_date}

AGENT STATUS:
{json.dumps(agent_status, indent=2)}

ALL AGENT OUTPUTS:
{json.dumps(agent_outputs, indent=2)}

Generate the complete markdown report following the exact template.
Calculate the composite score using the weighted formula.
Write a detailed recruiter recommendation.
Set report_path to: reports/{safe_name}_linkedin_report.md"""

    result = await run_agent(
        agent_name="LinkedIn Report Compiler",
        system_prompt=SYSTEM_PROMPT,
        user_content=user_content,
        response_schema=LinkedInReportOutput,
        model=MODEL_PRO,
    )

    if result:
        report_path = REPORTS_DIR / f"{safe_name}_linkedin_report.md"
        try:
            report_path.write_text(result.report_markdown, encoding="utf-8")
            result.report_path = str(report_path)
            logger.info(f"✅ LinkedIn Report written to: {report_path}")
        except Exception as e:
            logger.error(f"Failed to write LinkedIn report: {e}")
            result.report_path = f"ERROR: {e}"

        logger.info(
            f"✅ LinkedIn Report complete. "
            f"Grade: {result.grade.value}, Score: {result.composite_score}/10, "
            f"Verdict: {result.verdict.value}"
        )

    return result
