"""Add domain knowledge base

Revision ID: 0b0193337f3c
Revises: 6bd9c8db652f
Create Date: 2026-05-01 09:45:00.258484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b0193337f3c'
down_revision: Union[str, Sequence[str], None] = '6bd9c8db652f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_knowledge_base',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.TEXT(), nullable=False),
    sa.Column('source_file', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_knowledge_base')
    # ### end Alembic commands ###
