"""sync models with db

Revision ID: c56dacc53f33
Revises: f9e1dfd55cc4
Create Date: 2026-04-24 08:15:27.487976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c56dacc53f33'
down_revision: Union[str, Sequence[str], None] = 'f9e1dfd55cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hiring_reports')
    op.drop_index(op.f('interview_questions_session_id_idx'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.add_column('applications', sa.Column('shortlisted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('interview_deadline', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('applications', 'cover_note',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               existing_server_default=sa.text("'applied'::text"))
    op.alter_column('applications', 'fit_reasoning',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('applications_candidate_id_idx'), table_name='applications')
    op.drop_constraint(op.f('applications_job_id_candidate_id_key'), 'applications', type_='unique')
    op.drop_index(op.f('applications_job_id_idx'), table_name='applications')
    op.drop_index(op.f('applications_status_idx'), table_name='applications')
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_candidate_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('applications', 'job_posted_at')
    op.drop_column('applications', 'application_deadline')
    op.alter_column('candidates', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('candidates', 'full_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('candidates_user_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.alter_column('companies', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('companies', 'industry',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('companies_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    op.add_column('interview_sessions', sa.Column('deadline_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('interview_sessions', 'application_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('interview_sessions', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('interview_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('interview_sessions_application_id_idx'), table_name='interview_sessions')
    op.drop_constraint(op.f('interview_sessions_application_id_key'), 'interview_sessions', type_='unique')
    op.drop_constraint(op.f('interview_sessions_application_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'applications', ['application_id'], ['id'])
    op.drop_column('interview_sessions', 'recording_url')
    op.drop_column('interview_sessions', 'scheduled_at')
    op.drop_column('interview_sessions', 'room_url')
    op.drop_column('interview_sessions', 'ended_at')
    op.drop_column('interview_sessions', 'transcript')
    op.drop_column('interview_sessions', 'started_at')
    op.add_column('jobs', sa.Column('pipeline_triggered', sa.Boolean(), nullable=False))
    op.add_column('jobs', sa.Column('max_shortlist', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('min_fit_score', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('job_posted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('application_deadline', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('jobs', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('jobs', 'requirements',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('jobs', 'location',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('jobs', 'job_type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('notifications_user_id_is_read_idx'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('notifications_user_id_is_read_idx'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('jobs', 'job_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'location',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'requirements',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('jobs', 'application_deadline')
    op.drop_column('jobs', 'job_posted_at')
    op.drop_column('jobs', 'min_fit_score')
    op.drop_column('jobs', 'max_shortlist')
    op.drop_column('jobs', 'pipeline_triggered')
    op.add_column('interview_sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('room_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('interview_sessions', sa.Column('recording_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_application_id_fkey'), 'interview_sessions', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('interview_sessions_application_id_key'), 'interview_sessions', ['application_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('interview_sessions_application_id_idx'), 'interview_sessions', ['application_id'], unique=False)
    op.alter_column('interview_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_sessions', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('interview_sessions', 'application_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('interview_sessions', 'deadline_at')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_id_fkey'), 'companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'logo_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'industry',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('companies', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_user_id_fkey'), 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('candidates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'linkedin_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('candidates', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('applications', sa.Column('application_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('job_posted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_candidate_id_fkey'), 'applications', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('applications_status_idx'), 'applications', ['status'], unique=False)
    op.create_index(op.f('applications_job_id_idx'), 'applications', ['job_id'], unique=False)
    op.create_unique_constraint(op.f('applications_job_id_candidate_id_key'), 'applications', ['job_id', 'candidate_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('applications_candidate_id_idx'), 'applications', ['candidate_id'], unique=False)
    op.alter_column('applications', 'applied_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'fit_reasoning',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'applied'::text"))
    op.alter_column('applications', 'cover_note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('applications', 'interview_deadline')
    op.drop_column('applications', 'shortlisted_at')
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('was_asked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("question_type = ANY (ARRAY['technical'::text, 'behavioral'::text, 'resume_gap'::text, 'follow_up'::text])", name=op.f('interview_questions_question_type_check')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('interview_questions_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_questions_pkey'))
    )
    op.create_index(op.f('interview_questions_session_id_idx'), 'interview_questions', ['session_id'], unique=False)
    op.create_table('hiring_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strengths', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("recommendation = ANY (ARRAY['strong_hire'::text, 'hire'::text, 'maybe'::text, 'reject'::text])", name=op.f('hiring_reports_recommendation_check')),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name=op.f('hiring_reports_confidence_score_check')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('hiring_reports_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hiring_reports_pkey')),
    sa.UniqueConstraint('application_id', name=op.f('hiring_reports_application_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
