"""update_interview_models

Revision ID: e28a369c17f3
Revises: 8769bb49450c
Create Date: 2026-04-25 08:42:58.595328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e28a369c17f3'
down_revision: Union[str, Sequence[str], None] = '8769bb49450c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop existing table if it exists to ensure clean schema for new fields
    op.execute("DROP TABLE IF EXISTS interview_questions CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_audio_url', sa.TEXT(), nullable=True),
    sa.Column('answer_text', sa.TEXT(), nullable=True),
    sa.Column('answer_audio_url', sa.TEXT(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.Column('was_asked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('interview_sessions', sa.Column('current_question_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('interview_sessions', sa.Column('total_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('interview_sessions', sa.Column('report_summary', sa.TEXT(), nullable=True))
    op.add_column('interview_sessions', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'completed_at')
    op.drop_column('interview_sessions', 'report_summary')
    op.drop_column('interview_sessions', 'total_score')
    op.drop_column('interview_sessions', 'current_question_number')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
