"""baseline existing schema

Revision ID: f9e1dfd55cc4
Revises: 
Create Date: 2026-04-21 10:16:13.587443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9e1dfd55cc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hiring_reports')
    op.drop_index(op.f('interview_questions_session_id_idx'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_table('jobs')
    op.drop_index(op.f('interview_sessions_application_id_idx'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('applications_candidate_id_idx'), table_name='applications')
    op.drop_index(op.f('applications_job_id_idx'), table_name='applications')
    op.drop_index(op.f('applications_status_idx'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('notifications_user_id_is_read_idx'), table_name='notifications')
    op.drop_table('notifications')
    op.alter_column('candidates', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('candidates', 'full_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('candidates_user_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.drop_column('candidates', 'resume_embedding')
    op.drop_column('candidates', 'skills')
    op.alter_column('companies', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('companies', 'industry',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('companies_user_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_user_id_fkey'), 'companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'logo_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'industry',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('companies', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('candidates', sa.Column('skills', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('resume_embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_user_id_fkey'), 'candidates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('candidates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'resume_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'resume_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'linkedin_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidates', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('candidates', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("type = ANY (ARRAY['application_update'::text, 'interview_scheduled'::text, 'report_ready'::text])", name=op.f('notifications_type_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('notifications_user_id_is_read_idx'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cover_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'applied'::text"), autoincrement=False, nullable=True),
    sa.Column('fit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fit_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['applied'::text, 'screening'::text, 'interview_scheduled'::text, 'interviewed'::text, 'recommended'::text, 'rejected'::text])", name=op.f('applications_status_check')),
    sa.CheckConstraint('fit_score >= 0 AND fit_score <= 100', name=op.f('applications_fit_score_check')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('applications_candidate_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('applications_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('applications_pkey')),
    sa.UniqueConstraint('job_id', 'candidate_id', name=op.f('applications_job_id_candidate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('applications_status_idx'), 'applications', ['status'], unique=False)
    op.create_index(op.f('applications_job_id_idx'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('applications_candidate_id_idx'), 'applications', ['candidate_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('room_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])", name=op.f('interview_sessions_status_check')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('interview_sessions_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_sessions_pkey')),
    sa.UniqueConstraint('application_id', name=op.f('interview_sessions_application_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('interview_sessions_application_id_idx'), 'interview_sessions', ['application_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('job_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("job_type = ANY (ARRAY['full-time'::text, 'part-time'::text, 'contract'::text, 'internship'::text])", name=op.f('jobs_job_type_check')),
    sa.CheckConstraint("status = ANY (ARRAY['open'::text, 'closed'::text, 'paused'::text])", name=op.f('jobs_status_check')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('jobs_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('was_asked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("question_type = ANY (ARRAY['technical'::text, 'behavioral'::text, 'resume_gap'::text, 'follow_up'::text])", name=op.f('interview_questions_question_type_check')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('interview_questions_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_questions_pkey'))
    )
    op.create_index(op.f('interview_questions_session_id_idx'), 'interview_questions', ['session_id'], unique=False)
    op.create_table('hiring_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strengths', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("recommendation = ANY (ARRAY['strong_hire'::text, 'hire'::text, 'maybe'::text, 'reject'::text])", name=op.f('hiring_reports_recommendation_check')),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name=op.f('hiring_reports_confidence_score_check')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('hiring_reports_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hiring_reports_pkey')),
    sa.UniqueConstraint('application_id', name=op.f('hiring_reports_application_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
